sudo: required
services:
  - docker

before_install:
  - docker build -t yilengyao/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run yilengyao/react-test npm test -- --coverage

after_success:
  - docker build -t yilengyao/multi-client ./client
  - docker build -t yilengyao/multi-nginx ./nginx
  - docker build -t yilengyao/multi-server ./server
  - docker build -t yilengyao/multi-worker ./worker
  # Log in to the docker CLI
  - echo "${DOCKER_PASSWORD:?}" | docker login -u "${DOCKER_ID:?}" --password-stdin 
  # Take those images and push them to docker hub
  - docker push yilengyao/multi-client
  - docker push yilengyao/multi-nginx
  - docker push yilengyao/multi-server
  - docker push yilengyao/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-052994497551"
  bucker_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY